# Netlify Configuration for Multiverse Platform Portal Exchange

# Build settings
[build]
  # Directory to publish (the static site or app)
  publish = "frontend/dist"
  
  # Default build command
  command = "npm run build"
  
  # Directory with the serverless functions
  functions = "backend/functions"

# Redirects and rewrites
[[redirects]]
  # Redirect all API requests to serverless functions
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  # SPA fallback - redirect all requests to index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set on all pages
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; connect-src 'self' https://*.mongodb.net;"
    
# Environment variables
[build.environment]
  # Set Node version
  NODE_VERSION = "18"
  
  # Set environment to production
  NODE_ENV = "production"
